name: Node.js Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps: 
       - name : 'BeFore'
         run: ls

       - uses: actions/checkout@v3
       
       - name: 'After'
         run: ls -a 