name: Node.js Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps: 
       - uses: actions/checkout@v3
       
       - name: 'Login To Docker hub'
         run: docker login --username ${{secrets.DOCKER_NAME}}  --password ${{secrets.DOKER_TOKEN}}  
         
       - name: "Building docker image " 
         run: docker build -t   ${{secrets.DOCKER_NAME}}/myimage .

       - name: "Push to Docker hub"  
         run: docker push  ${{secrets.DOCKER_NAME}}/myimage
